#!/usr/bin/env bash
#Installing your load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
        bind *:80
        mode http
        default_backend Web_Servers
backend Web_Servers
        balance roundrobin
        mode http
	server 5496-web-01 18.207.93.144:80 check
	server 5496-web-02 54.145.227.135:80 check
EOF

sudo service haproxy restart
